Develop
SidorovKV/java-filmorate pull request #27
Opened 2023-05-01 10:51 UTC by SidorovKV

2023-05-03 20:53 UTC, alexache requested changes

2023-05-03 20:53 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public DirectorController(DirectorService directorService) {
Где-то конструктор помечен с помощью @Autowired, где-то нет. Оба варианта допустимы, лучше использовать один повсеместно

2023-05-03 20:53 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        var optDirector = directorDAO.findById(id);
Этот подход к удалению тоже отличается от удаления других сущностей, стоит сделать что-то в одном стиле

2023-05-03 20:53 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return new ArrayList<>();
Может это должно заканчиваться исключением?

2023-05-03 20:53 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDAO.java
> +            "(SELECT ARRAY_AGG(name) FROM genre WHERE ID IN (SELECT genre_id FROM FILM_GENRE WHERE film_id = f.ID)) AS genres, " +
Все таки тройной уровень вложенности запросов уже пугает, может все же стоит попытаться это решить через джоин? Для режиссеров джоин должен легко помочь

2023-05-03 20:53 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public Collection<Review> findReviewsByFilm(@RequestParam(required = false) Long filmId, @RequestParam(required = false) Long count) {
Может стоит добавить значение по умолчанию для count?  Например, 10

2023-05-03 20:53 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    @PostMapping(consumes = "application/json")
Чем этот метод особенный, что только у него указан consumes?

2023-05-03 20:53 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        if (review.getUserId() < 0) {
Почему бы не сделать такие проверки аннотациями на Review?

2023-05-03 20:53 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewDAO.deleteById(id);
Подход по удалению тут тоже немного отличается - вместо проверки количества измененных значений напрямую ищется по айди, хорошо бы иметь один подход

2023-05-03 20:53 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            Review daoReview = findReview(id);
(опционально) Иначе можно делать наоборот - сначала получать объект отзыва по айди, на нем менять только тело отзыва и "положительность", а остальные поля оставлять от считанного из базы. Но разница не очень велика

2023-05-03 20:53 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDAO.java
> +            title = null;
Немного не понял логики с null, поясните, пожалуйста?

2023-05-03 20:53 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Collection<Film> recommendations = filmDAO.getRecommendations(userId);
Уже поэтому логичнее, чтобы этот метод был в FilmService, нежели в UserService

2023-05-03 20:53 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDAO.java
> +                "                                                  (SELECT film_id FROM liked WHERE user_id=?) " +
Очень очень много вложенности, лучше обойтись без такого количества вложенных запросов, и лоигку сделать более плоской  - 

1. Найти пользователей с похожими лайками
2. Найти айди фильмов, которые они лайкнули, но который текущий юзер не лайкал
3. Получить объекты этих пользователей

2023-05-03 22:21 UTC, VMarvarik commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDAO.java
> +            title = null;
Здравствуйте!
COALESCE() всегда возвращает значение первого не null аргумента, поэтому, если нам необходимо выполнить поиск по названию, мы передаем в него null и _WHERE COALESCE(null, LOWER(f.title)) LIKE LOWER(?)_ будет искать подстроку в названиях. То же самое с режиссером. Это позволяет использовать всего один запрос в бд (вместо 3 отдельных запросов для имени/режиссера/имени и режиссера).

2023-05-04 09:17 UTC, gosn1ck commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return new ArrayList<>();
нет, исключение в слое контроллера, 
![image](https://user-images.githubusercontent.com/116619669/236162293-589330e5-7faf-48ba-896a-a3c3d681c51d.png)

2023-05-04 11:53 UTC, SidorovKV commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDAO.java
> +            title = null;
Команда предложила немного изменить запрос. Кажется теперь он стал более читаемым.

2023-05-04 12:31 UTC, SidorovKV commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        if (review.getUserId() < 0) {
Я бы с радостью, но тесты требуют на @NotNull "Status code is 400", а на явно неверный(отрицательный) айди юзера/фильма "Status code is 404". Делать проверку на уровне сервиса, пытаясь вызвать сущности из базы по айди кажется излишним. Попытаться создать запись в бд с явно неверными айди и поймать-пробросить эксепшн тоже не допускают тесты. Сработает автоинкремент.

2023-05-05 17:29 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            return new ArrayList<>();
Зачем тогда этот else?

2023-05-05 17:35 UTC, alexache approved these changes

2023-05-05 17:47 UTC, merged