First try
SidorovKV/java-filmorate pull request #3
Opened 2023-03-01 18:58 UTC by SidorovKV

2023-03-02 21:40 UTC, alexache requested changes

2023-03-03 11:44 UTC, SidorovKV commented on pom.xml
> +			<groupId>eu.ralph-schuster</groupId>
Это я не доконца разобрался с maven central repository. Получается взял какую-то кастомную сборку jackson'a, а не оригинальную. Вместо gson взял jackson, так как даты преобразует, как нужно сразу "из коробки". Заменил на оригинальную библиотеку.

2023-03-03 12:04 UTC, SidorovKV commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (emails.contains(user.getEmail())) {
HasSet только на ум приходит

2023-03-03 12:15 UTC, SidorovKV commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            emails.remove(users.get(user.getId()).getEmail());
Имеется в виду под else внести? Тогда лучше будет инвертировать конструкцию.

2023-03-03 22:34 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            emails.remove(users.get(user.getId()).getEmail());
Не совсем. Я про то что все вызовы users.get(user.getId()) можно заменить на един единственный с сохранением в переменную, так же и containsKey можно заменить на проверку значения этой переменной

2023-03-03 22:35 UTC, alexache approved these changes

2023-03-03 22:35 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    public static void beforeAll() {
(опционально) на всякий случай я говорил про модификаторы у полей. У тест методов допустимо иметь дефольтный модификатор доступа

2023-03-04 07:29 UTC, merged