T3-10 Add friends and likes
SidorovKV/java-filmorate pull request #4
Opened 2023-03-11 14:29 UTC by SidorovKV

2023-03-12 07:35 UTC, alexache requested changes

2023-03-12 07:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        String exceptionMessage = e.getMessage();
(опционально) Какая-та сложная логика парсинга исключений - точно ли нужны такие сложности?

2023-03-12 07:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private final UserStorage userStorage;
На мой взгляд. есть некоторая проблема с распределением ответственности классов. Контроллеры и сервисы по сути ничего не делают, а сторадж делает все. 
Давай определимся с тем, что сторадж должен следовать single responsibility и должен заниматься только хранением/работой со своей сущностью - никаких вызовов в стороние стораджи. 
Тогда у сервисов появится хоть какая-та работа в виду взаимодействия с разными стораджами

2023-03-12 07:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        //Нужна ли проверка на неотрицательность? Или limit() сам справляется?
справится. будет исключение, доп проверка не требуется, либо (по желанию) ее можно сделать в контроллере

2023-03-12 07:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new ReleaseDateValidationException("Ошибка при создании записи о фильме:" +
(опционально) Полное дублирование текста выглядит излишним, может исключение логгировать в ErrorHandler?

2023-03-12 07:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (film.getReleaseDate().isBefore(FIRST_FILM_EVER_RELEASE)) {
Валидации относятся к сфере работы контроллера, а не стораджа. То есть возвращаясь к single responsibility: 
контроллер валидирует входные данные (без запросов к стораджу), вызывает сервис
сервис занимается взаимодействием между разными стораджами, возможно какой-то доп обработкой данных
сторадж только хранит/возвращает/фильтрует данные

2023-03-12 07:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        User user = users.get(id);
Такую логику тоже логичнее писать в сервисе. чтобы сторадж занимался более базовыми запросами

2023-03-12 07:35 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            if (users.get(user.getId()).getEmail().equals(user.getEmail())) {
users.get/users.containsKey вызывает множество раз, может можно вызвать единожды?

2023-03-12 08:22 UTC, SidorovKV commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        String exceptionMessage = e.getMessage();
Они (сложности) не обязательны, но наружу уходит короткое читаемое сообщение об ошибке, а не подробное многострочное из валидатора.

2023-03-12 09:44 UTC, SidorovKV commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private final UserStorage userStorage;
Понятно.
Надеюсь теперь правильно ответственности распределил.

2023-03-12 09:44 UTC, SidorovKV commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new ReleaseDateValidationException("Ошибка при создании записи о фильме:" +
+

2023-03-12 10:03 UTC, SidorovKV commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +            if (users.get(user.getId()).getEmail().equals(user.getEmail())) {
Можно)

2023-03-12 10:03 UTC, SidorovKV commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    private final UserStorage userStorage;
Понятно.
Надеюсь теперь правильно ответственности распределил.

2023-03-12 10:45 UTC, SidorovKV commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (film.getReleaseDate().isBefore(FIRST_FILM_EVER_RELEASE)) {
Остался не совсем понятым один момент: если мы выносим логику по созданию выборок (общие друзья, самые популярные фильмы и прочее) в сервисы, то почему не выносим так же и возращение сущности по айди или списка всех сущностей хранилища?
Надеюсь когда-нибудь достигну просветления в single responsibility)

2023-03-13 16:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (film.getReleaseDate().isBefore(FIRST_FILM_EVER_RELEASE)) {
Это пока выглядит немного надуманным со стораджом в виде мапы, а когда это станет базой данных, то все встанет на свои места. 
Почему будет плохо делать все в сервисе - потому что это будет дорого, база данных оптимизированна на такие запросы и будет делать это быстрее, нежели сервис будет бегать по всему списку и искать сам.
Почему это важно уже сейчас? Потмоу что лучше закладывать понятный дизайн и распределение ролей со старта, так будет легче в дальнейшем

2023-03-13 16:43 UTC, alexache requested changes

2023-03-13 16:43 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +    Map<Long, User> getUsersRegistry();
Вот это не очень хорошо, это ты затачиваешь интерфейс стораджа на конкретную реализацию в виде мапы, А что если будет реализация не через мапу, то придется переписывать интерфейс?
getById будет лучше

2023-03-13 16:43 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> -        Film film = films.get(id);
Если приходится делать getFilmsRegistry().get(id) вместо findFilm(id) только из-за исключения, то логично делать эту обработку бросания исключения в сервисею То есть Optional<Film> findFilm(Long id), а в сервисе при необходимости Film film = findFIlm(id).orElseThrow(() -> new UnknownEntituException());

2023-03-13 16:43 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        User user = userStorage.getUsersRegistry().get(id);
Напи ал комментарий про использование регистра из стораджа в сторадже

2023-03-13 17:53 UTC, SidorovKV commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        String exceptionMessage = e.getMessage();
А ненадёжность в чём заключается? В том, что MethodArgumentNotValidException перепишут?

2023-03-13 17:53 UTC, SidorovKV commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        String exceptionMessage = e.getMessage();
А ненадёжность в чём заключается? В том, что MethodArgumentNotValidException перепишут?

2023-03-14 12:09 UTC, merged